### ISSUE TITLE
Reverse relationships

### ISSUE THREAD

**Issue by SethCurry** [SethCurry/cmgraph#1]
There should be a function to automatically create reverse relationships.

Something resembling:

```
types:
  User:
    username: "string"
    member_of:
      type: "Team"
      reverse: "members"

  Team:
    name: "string"
    members:
      type: "User"
      reverse: "member_of"
```

Where you could specify "member_of" on a User, and have a "members" relationship created on the Team automatically.
